# Generated by Django 2.0.1 on 2018-08-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_audiomessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
