# Generated by Django 2.0.1 on 2018-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
